### ISSUE TITLE
nav.item doesn't passthrough query params v3.0.0-rc.0

### ISSUE THREAD

**Issue by aklkv** [kaliber5/ember-bootstrap#852] opened 2019-07-08 11:31 UTC
With this template: 
```
<nav.item @linkTo={{array "lessons" (query-params filter="upcoming")}}>
  Upcoming Lessons
</nav.item>
```
I receive an error:
`More context objects were passed than there are dynamic segments`
It's probably a good idea to not use positional params in this case since API for angel bracket LinkTo component has changed so each paras is passed as individual arguments.

**Comment by jelhan** [comment] 2019-07-08 11:37
Could you provide a reproduction as Ember Twiddle oder CodeSandbox? There is a passing test, which should cover this one:

https://github.com/kaliber5/ember-bootstrap/blob/138af55c55d941794b669ebaa392f005541007f6/tests/integration/components/bs-nav/item-test.js#L60-L65

**Comment by aklkv** [comment] 2019-07-08 12:14
@jelhan https://codesandbox.io/s/my-app-x7oc9 
Let me know if you need anything else

**Comment by jelhan** [comment] 2019-07-08 12:24
Thanks. The bug is not triggered by rendering but clicking the nav link. That one does not seem to be covered by tests.

I'm not sure if we should introduce that custom syntax at all. When we did it, https://github.com/emberjs/rfcs/blob/master/text/0459-angle-bracket-built-in-components.md wasn't there yet. But since that RFC is merged (and shipped in 3.10), we should refactor to match that naming.

There isn't any polyfill for `<LinkTo>` yet. So we might need to map the arguments to `{{link-to}}` on our own.

**Comment by aklkv** [comment] 2019-07-08 12:30
@jelhan let me know if you need help with that I can have a look this week

**Comment by lifeart** [comment] 2019-07-08 12:32
kinda solution https://ember-twiddle.com/#/5707fb3de33a8db746ceaa76245537cd?openFiles=components.my-link-to.js%2C

**Comment by simonihmig** [comment] 2019-07-08 17:17
> I'm not sure if we should introduce that custom syntax at all. When we did it, https://github.com/emberjs/rfcs/blob/master/text/0459-angle-bracket-built-in-components.md wasn't there yet. But since that RFC is merged (and shipped in 3.10), we should refactor to match that naming.

I agree. We should fix that before a stable 3.0.0 release!

> let me know if you need help with that I can have a look this week

@aklkv help is always welcome for sure! 😀 If you want to start work on a PR, please announce it here, so we don't duplicate work!

**Comment by simonihmig** [comment] 2019-07-12 18:38
This lays the ground work (polyfill for `<LinkTo>`): https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/pull/72

When that has landed, the changes here should be pretty straightforward...

**Comment by simonihmig** [comment] 2019-07-19 21:05
A PR is prepared for this: #861

**Closed** 2019-08-06 08:32 UTC
Labels: bug
