### ISSUE TITLE
Could not find module`bs-bootstrap`

### ISSUE THREAD

**Issue by drewcovi** [kaliber5/ember-bootstrap#899] opened 2019-09-26 16:16 UTC
All other components I've used thus far appear to be working great besides BsButton, if there are any known workarounds please let me know.

Thanks!

```handlebars
<BsButton @type="primary" @icon="glyphicon glyphicon-download">
        Downloads
 </BsButton>
```

```console
Unhandled Promise Rejection: Error: Could not find module `ember-bootstrap/templates/components/bs-button` imported from `ember-bootstrap/components/base/bs-button
```
---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^3.0.0-rc.5 -> 3.0.0-rc.5
ember-cli: ~3.13.0 -> 3.13.0
bootstrap: ^4.3.1 -> 4.3.1
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: true
```

**Comment by jagzviruz** [comment] 2019-09-26 16:41
I ran into this issue earlier for `BsAccordion` earlier. Updating to `rc6` fixed it. It seems to obe due to cli version 3.13.

**Comment by jelhan** [comment] 2019-09-26 20:19
Duplicate of #881 .

**Closed by jelhan** 2019-09-26 20:19 UTC
