### ISSUE TITLE
Focus out is causing incorrect display of success on form element

### ISSUE THREAD

**Issue by BryanHunt** [kaliber5/ember-bootstrap#1017] opened 2020-03-13 19:11 UTC
```
Npm packages:
ember-bootstrap: ^3.1.1 -> 3.1.2
ember-cli: ~3.16.0 -> 3.16.0
bootstrap: ^4.3.1 -> 4.4.1
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: true
```

I'm trying to get ember-bootstrap working with ember-changeset-validations.  I have it basically working, but I've run into a couple of problems.  

The first is that if an element such as a text box is empty (you just clicked on it and never entered any text) and it looses focus, it will cause validations to be shown but the model hasn't been validated yet.  The result is the green border around the text box and a green check indicating the field is valid.  If you then click the submit model validation runs and the field(s) go from green to red.

The second problem will wait until I can root cause it.

**Comment by simonihmig** [comment] 2020-03-15 23:25
@BryanHunt are you using `ember-changeset` v3? If so, this seems like a duplicate of https://github.com/kaliber5/ember-bootstrap-changeset-validations/issues/17, and worked on https://github.com/kaliber5/ember-bootstrap-changeset-validations/pull/19 (as you already have found).

I'll close this here, as this more belongs to `ember-bootstrap-changeset-validations`. Feel free to reopen in case I misunderstood.

**Comment by jelhan** [comment] 2020-04-19 18:57
@BryanHunt Are you still seeing this issue with latest versions of ember-bootstrap, ember-changeset-validations and ember-bootstrap-changeset-validations? If so, please provide a reproduction as an Ember Twiddle, CodeSandbox or GitHub repository. Otherwise please close this issue.

**Comment by visoft** [comment] 2020-04-20 13:37
@jelhan I'm seeing the same as @BryanHunt. I have a simple form with 2 fields, one validated for presence and minLength. It's on autofocus. If I click on the other field that isn't validated and the first one loses focus, the is-valid class is there, showing the green border.

**Comment by visoft** [comment] 2020-04-20 13:41
Here is an example of the behavior: https://share.getcloudapp.com/NQuDegBB

**Comment by jelhan** [comment] 2020-04-20 13:51
> I have a simple form with 2 fields, one validated for presence and minLength. It's on autofocus. If I click on the other field that isn't validated and the first one loses focus, the is-valid class is there, showing the green border.

This is kind of expected. Validations are shown after specific events. Focus out event is the default one: https://www.ember-bootstrap.com/api/classes/Components.FormElement.html#property_showValidationOn

**Comment by visoft** [comment] 2020-04-20 14:13
But shouldn't it be invalid?

The field is `name`:

```
import { validatePresence, validateLength } from 'ember-changeset-validations/validators';
export default {
  name: [validatePresence(true), validateLength({ min: 4 })],
};
```

**Comment by jelhan** [comment] 2020-04-20 14:18
This wasn't clear from the video. Could you please create an Ember Twiddle, CodeSandbox or GitHub repository which reproduces the issue?

**Comment by visoft** [comment] 2020-04-21 23:16
@jelhan Here's a twiddle: https://ember-twiddle.com/0d0a0f211c818a5300b4deaac7e159d6?openFiles=validators.form%5C.js%2C Just click on the name field and tab or something, it turns green when it should be red.

**Comment by BryanHunt** [comment] 2020-04-22 18:52
Thanks @visoft for putting that example together.  I'm swamped right now.

**Comment by simonihmig** [comment] 2020-04-23 09:56
This seems wrong indeed. 

The docs validation example features a similar case: https://www.ember-bootstrap.com/#/components/forms, but this time using `ember-cp-validations`. There it is working as expected. So I would assume this is an issue of https://github.com/kaliber5/ember-bootstrap-changeset-validations.

Created an issue: https://github.com/kaliber5/ember-bootstrap-changeset-validations/issues/22, closing this.

**Closed by simonihmig** 2020-04-23 09:56 UTC

**Comment by visoft** [comment] 2020-04-26 16:38
Question regarding this, does ember-bootstrap attempt to set a value on the changeset when focusout is called? See https://github.com/poteto/ember-changeset-validations/pull/237#issuecomment-619563918
