### ISSUE TITLE
SassCompiler throws on ember-cli@3.4.0-beta.2

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#645] opened 2018-08-14 13:20 UTC
SassCompiler throws on a new project after installing ember-bootstrap using sass preprocessor on `ember-cli@3.4.0-beta.2`:

```
Sass Syntax Error (SassCompiler) in test-sass/styles/app.scss:2:1

Error: File to import not found or unreadable: ember-bootstrap/bootstrap.
        on line 2 of tmp/sass_compiler-input_base_path-gJWx1BJt.tmp/test-sass/styles/app.scss
>> @import "ember-bootstrap/bootstrap";
```

This is not a general issue of `ember-cli-sass`. I've verified that importing styles from ember-power-select works fine.

Steps to reproduce:
- upgrade ember-cli to 3.4.0-beta.2
- `ember new test-sass`
- `cd test-sass`
- `ember install ember-bootstrap --preprocessor=sass` (ignore the warning about unknown option)
- `rm app/styles/app.css`
- `ember build`

**Comment by simonihmig** [comment] 2018-08-17 23:49
Keeping this open here so others can find this, but it seems this is caused by that particular version of Ember CLI. Does not happen with 3.4.0-beta.1. See https://github.com/ember-cli/ember-cli/issues/7987

**Comment by simonihmig** [comment] 2018-08-29 07:56
This has been fixed now in Ember CLI on the latest beta and master branches, so closing this! 🎉

**Closed by simonihmig** 2018-08-29 07:56 UTC
