### ISSUE TITLE
BS-Tooltip makes link wander around

### ISSUE THREAD

**Issue by bluscreen** [kaliber5/ember-bootstrap#270] opened 2017-03-19 11:32 UTC
Hi, bs-tooltip has a bug with link-to helper i think:

```
  <div class="col-xs-3">
      {{#link-to "x"}}
        x
        {{bs-tooltip title="Anfrage annehmen"}}
      {{/link-to}}
      {{#link-to "y"}}
        y
        {{bs-tooltip title="Anfrage ablehnen"}}
      {{/link-to}}
    </div>
```

when i hover over x, y moves under x

screenshot: http://imgur.com/a/44C1Z

cheers
Daniel

**Comment by ashrafhasson** [comment] 2017-07-23 16:19
it also appears that `bs-tooltip` doesn't show when used inside an anchor element that has a computed style/class, like so:

```code
<a class="btn btn-circle btn-default {{if (can "delete item") "enabled" "disabled"}}">
  {{bs-tooltip title="something to delete"}}
  <i class="icon-trash"></i>
</a>
````
where the `can` helper computes a boolean while it works when embedded in a div element.
Not sure if this is related but worth investigating while at it.

Thanks,

**Comment by danidr** [comment] 2017-09-14 12:37
Can confirm this behaviour on 1.0.0-rc.2. Never had this problem on old beta versions though...

**Comment by simonihmig** [comment] 2017-09-18 18:07
Confirmed: this is caused by the `div` element that is added by `ember-wormhole`. Unfortunately it does not support being a tagless component (see https://github.com/yapplabs/ember-wormhole/issues/70), so there is currently no way to get rid of this `div`.

However in #437 there is a major refactoring of tooltips and popovers, that uses `ember-popper` and does not rely anymore on `ember-wormhole`. So when that lands, this issue should be solved! For now you can maybe add some CSS to hide the wormhole `div`, like `a > div { display: none }`.

Actually this issue should have been around since tooltip support was introduced, it was always relying on `ember-wormhole`... 🤔

**Comment by simonihmig** [comment] 2017-10-25 23:19
This problems should be fixed with the latest release, see the above comment. If you still encounter problems, feel free to reopen!

**Closed by simonihmig** 2017-10-25 23:19 UTC
Labels: bug
