### ISSUE TITLE
NPM hangs up upon installing Bootstrap 4

### ISSUE THREAD

**Issue by huberts** [kaliber5/ember-bootstrap#446] opened 2017-09-13 19:54 UTC
Hi!

There is an issue when I try to run `npm install`. I have created a project with following commands:
> ember new my-app
> cd my-app
> ember install ember-bootstrap@1.0.0-rc.1
> ember generate ember-bootstrap --bootstrap-version=4
> rm -rf node_modules
> rm package-lock.json
> npm install

I work with Windows, npm_5.3.0, ember-cli_2.15.1. The NPM freezes (but uses processor time) at:

> \ extract:core-js: sill extract babel-plugin-htmlbars-inline-precompile@0.2.3

Can anyone confirm the problem?

**Comment by simonihmig** [comment] 2017-09-13 20:51
Duplicate of #430

**Closed by simonihmig** 2017-09-13 20:51 UTC

**Comment by simonihmig** [comment] 2017-09-13 21:02
https://github.com/kaliber5/ember-bootstrap/pull/435 should have fixed this, somehow... (not released yet)
