### ISSUE TITLE
Subroutes and navigation

### ISSUE THREAD

**Issue by rstudner** [kaliber5/ember-bootstrap#195] opened 2017-01-05 18:56 UTC
<img width="207" alt="screen shot 2017-01-05 at 1 53 42 pm" src="https://cloud.githubusercontent.com/assets/209970/21693355/9647252a-d34e-11e6-9ea8-2e8619931d8f.png">
Screenshot attached.

```
      {{#bs-nav type="pills nav-stacked"}}
        <li class="menu-label"><a href="javascript:void(0);">Settings</a></li>
        {{#bs-nav-item}}
          {{#link-to "settings.assemblers"}}Assemblers{{/link-to}}
        {{/bs-nav-item}}
        {{#bs-nav-item}}
          {{#link-to "settings.security-devices"}}Security Devices{{/link-to}}
        {{/bs-nav-item}}
        {{#bs-nav-item}}
          {{#link-to "settings.users"}}Users{{/link-to}}
        {{/bs-nav-item}}
        {{#bs-nav-item}}
          {{#link-to "settings.users.show" currentUser}}My profile{{/link-to}}
        {{/bs-nav-item}}
      {{/bs-nav}}
```

So, the issue, is that if I go to settings.users.show, it is highlighting BOTH of the nav items (as per screenshot).

Is this "right"?  Any thoughts on work arounds?

**Comment by simonihmig** [comment] 2017-01-05 20:16
I think this is right. The active state is taken from the standard `link-to` component, which is also active for a parent route if it has an active child route. To match the route hierarchy one would nest another nav inside the `settings.users` nav-item, and then this would make sense: an active `settings.users.show` sub nav item within an active `settings.users` parent nav item.

What happens if you link to `settings.users.index` instead of `settings.users`?

**Comment by simonihmig** [comment] 2017-01-05 20:16
Closing this as it is not a bug, but we can still comment on this...

**Closed by simonihmig** 2017-01-05 20:16 UTC

**Comment by rstudner** [comment] 2017-01-05 20:20
Thanks so much for the response / sorry for using github issues for q&a (though it does help for later searching by others hah)

Setting it to settings.users.index totally worked.  Not sure why on earth I didn't think of that.  

I've never actually tried nested nav-items, so i'll have to explore/experiment on how that works.. I presume that is for doing a dropdown/flyout menu so the parent and child are both high lighted correctly.

Super excited to upgrade to 1.0 and am ready/happy to help w/ the eventual 4.0 migration (I'm coming back to ember since like 1.3, so I thought i'd have made too much noise with a smart contextual component cutover re: 1.0 so I stayed back in order to lessen noise :)
