### ISSUE TITLE
ember-cli bug when installing  ember-bootstrap

### ISSUE THREAD

**Issue by coucal** [kaliber5/ember-bootstrap#211] opened 2017-01-23 00:42 UTC
Trying to install ember-boostrap  I get this message : 

> Installed addon package.
> [                 .] / runTopLevelLifecycles: sill install printInstalled

and installation stops

I know it is an ember-cli issue while trying to overwrite some existing file : https://github.com/ember-cli/ember-cli-mocha/issues/159

Any idea to workaround ? Manually terminating installation..
BTW when I clone demo app it works fine

**Comment by simonihmig** [comment] 2017-01-23 10:57
Thanks @coucal for pointing this out. Have not seen this myself, but pressing enter seems to be the workaround: https://github.com/ember-cli/ember-cli-mocha/issues/159#issuecomment-267383103

Will close this as the issue is within ember-cli. Should be fixed with 2.11.

**Closed by simonihmig** 2017-01-23 10:57 UTC
