### ISSUE TITLE
Add class "flex-wrap" to Components.Tab

### ISSUE THREAD

**Issue by absemetov** [kaliber5/ember-bootstrap#290] opened 2017-04-02 17:32 UTC
Tab navs now wrapping

**Comment by simonihmig** [comment] 2017-04-12 09:41
Can you please explain what the problem is, and what this fixes? Is it related to Bootstrap4?

**Comment by absemetov** [comment] 2017-05-08 09:34
http://stackoverflow.com/questions/42843854/bootstrap-4-tabs-not-wrapping

**Comment by absemetov** [comment] 2017-05-08 09:41
I add http://www.ember-bootstrap.com/api/files/addon_components_base_bs-nav.js.html#l6
````
classNames: ['nav', 'flex-wrap'],
````

**Comment by simonihmig** [comment] 2017-05-16 07:13
Not sure if the behavior is a flaw in the latest Bootstrap 4 CSS (that might be fixed sometime), or "by design". And if ember-bootstrap should try to "fix" it or not?

Either 
* fix it in ember-bootstrap by adding the proposed changes
* or rely on the user to add it, if he wants it. You can easily extend any component in your app and just add the missing pieces, like `classNames: ['flex-wrap']` in this case

@srvance any opinion on thins one?

**Comment by simonihmig** [comment] 2017-08-19 19:56
Seems this was added now in Bootstrap 4.0.0-beta.1: https://github.com/twbs/bootstrap/pull/21824/files. Support is coming as part of #410, so closing now.

**Closed by simonihmig** 2017-08-19 19:56 UTC
Labels: Bootstrap 4, enhancement
