### ISSUE TITLE
Unable to set html attributes for dropdown-divider

### ISSUE THREAD

**Issue by fran-worley** [kaliber5/ember-bootstrap#1262] opened 2020-09-25 09:46 UTC
Up until version v4.1.2, we had a `data-test` attribute set on the dropdown divider. This attribute is no longer rendered. Is this expected behaviour? If so I can change our tests to pickup the `.dropdown-divider` class but I thought I'd raise it incase this was an unexpected consequence of the move to co-located templates.

I'd love to pinpoint exactly what version this started (I know it works in v4.0.0), but I can't load v4.0.1 or v4.1.0 due to issues with the modifier changes that raise this error:

`Uncaught (in promise) Error: Compile Error: Unexpected Modifier ref @ 0..0`

**Comment by simonihmig** [comment] 2020-09-26 16:12
>  I thought I'd raise it incase this was an unexpected consequence of the move to co-located templates.

Have you overridden the component/template in your app before? If so, this would be a duplicate of #1258 

However it indeed does not work AFAICT, as `...attributes` is missing [here](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-dropdown/menu/divider.hbs#L1). But this would have materialized with Version 4.0.0, as that introduced tagless components. Are you sure it worked in 4.0.0?

Anyways, we need to fix this. @fran-worley up for a PR? 😀

Apart from adding `...attributes` we should add a simple test, similar to what we usually have for applying HTML attributes for most other components.

**Comment by fran-worley** [comment] 2020-10-05 16:06
@simonihmig so I've tracked this down. We were overriding the template to add in the ...attributes which of course no longer works now that you can't override templates. I'll raise a PR for this ASAP 😄

**Closed** 2020-10-06 21:33 UTC
Labels: bug
