### ISSUE TITLE
bs-form: prevent native submit event from bubbling

### ISSUE THREAD

**Issue by IBue** [kaliber5/ember-bootstrap#796] opened 2019-04-01 17:06 UTC
Since ember-bootstrap **2.1.0** (5be69745defb22dba42b70b4d418df6696dd6ed5) bs-form's internal submit handler indirectly calls the user provided onSubmit closure action through a promise chain and returns undefined. This won't prevent the form's native submit event from bubbling up and trigger a containing component's method (not action) named "submit".

Twiddle:
https://ember-twiddle.com/b7853de6d9bdd76fd3032bc5e1b86a4a

Solution:

- return false from internal submit handler
- call event.stopPropagation() in addition to event.preventDefault() within internal submit handler

**Comment by jelhan** [comment] 2019-04-09 20:15
@IBue Thanks for reporting that bug. Was able to reproduce.

Your Twiddle is a little bit confusing cause `submit` method is executed in `submitMyFormAction`. Therefor I wasn't surprised that `modifyMyModel` action is executed - but I was after I had removed the execution of `submit` from `submitMyAction`.

Refactored that Twiddle for readability: https://ember-twiddle.com/508dffdc6aa3b8a09b863341d73b07b6?openFiles=components.my-form.js%2C

**Comment by simonihmig** [comment] 2019-04-09 21:38
Not sure tbh why we would expect the event to not bubble?

Is it only because of this example of a component having a `submit` method, which probably was not meant to handle submit events? As `Ember.Component` allows to react on events by adding an event handler method with the same name as the event type, you should reserve those methods indeed only for event handlers. Same could happen with a `change` method, when some child element is an `<input>`. But I don't think you should always prevent event bubbling because of this!?

**Comment by jelhan** [comment] 2019-04-12 12:24
@simonihmig Very good point. Since HTML spec does not allow nested forms there doesn't seem valid use cases for not bubbling the action. Naming issue is actually a good showcase why glimmer components are needed. :smilele:

We might want to ensure that the submit event bubbles. Will update #799 accordingly.

**Comment by simonihmig** [comment] 2019-04-22 16:11
Closing this. @IBue as mentioned above, the solution should IMHO be to not use a `submit` method in your component (for doing this things not related to handling submit events), which has a naming conflict with a submit event handler.

**Closed by simonihmig** 2019-04-22 16:11 UTC
