### ISSUE TITLE
Passing an ID into a modal?

### ISSUE THREAD

**Issue by step1041** [kaliber5/ember-bootstrap#343] opened 2017-06-05 05:29 UTC
Appologies if this has been asked before or if this isn't the right place, I was looking for an answer to the following question.

I'm working on a component that uses Ember's each function to generate a table from some data. I then want to have a button on each row that will open a modal for me to edit/delete the data in that row. 

For this to happen I would need to pass in the ID of the row that the modal was clicked on. Is it possible for me to do this? I didn't see any direct way in the docs. (http://www.ember-bootstrap.com/api/classes/Components.Modal.html)

**Comment by simonihmig** [comment] 2017-06-05 11:46
Not sure I understand this. Can you share some code, please? 

And btw, for more general questions there is the `#-bootstrap` channel on the Ember Slack!

**Comment by step1041** [comment] 2017-06-06 03:04
Sorry, must have missed the Slack link. I'll use that next time for sure!

[game-table.hbs.txt](https://github.com/kaliber5/ember-bootstrap/files/1053692/game-table.hbs.txt)

I have attached the component I am working on. There is a table that displays the model data with a 'modify' button on each row in the table. That would then open a modal for me to edit the data or delete it. Maybe I'm wrong, but I would need to pass in the id of the data that was clicked on into the modal for me to then use Ember's findRecord function to get the data to be edited or deleted. 

Thanks for the help!

**Comment by simonihmig** [comment] 2017-06-06 10:31
I think you could call a custom action on your `game-table.js` (I guess a component, or controller?):

```hbs
<td>{{#bs-button onClick=(action "openModal" game)}}Open Modal{{/bs-button}}</td>
```

This action would receive the game model corresponding to the row you clicked on as its parameter, which you can use to assign the selected game (e.g `this.set('selectedGame', game)`) and open the modal. Then you can use `selectedGame` in the modal's body to bid to the needed properties.

**Comment by simonihmig** [comment] 2017-06-06 10:31
Closing this as it is not a bug/issue in e-b itself...

**Closed by simonihmig** 2017-06-06 10:31 UTC
Labels: question
